Docs(connector): Updating/Improving the DBLP docs with template params
sfu-db/dataprep pull request #383
Opened 2020-10-06 23:33 UTC by pallavibharadwaj

DBLP documentation was incorrect and did not include the latest changes. Also, updating the docs to reflect the use of template params like `first_name` and `last_name`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [x] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2020-10-07 16:03 UTC, peiwangdb approved these changes

2020-10-07 19:50 UTC, dovahcrow requested changes
LGTM! @pallavibharadwaj Can you rebase the branch to the latest develop branch?

2020-10-11 21:11 UTC, pallavibharadwaj commented
> LGTM! @pallavibharadwaj Can you rebase the branch to the latest develop branch?

@dovahcrow Done! Please let me know if I didn't do it right.

2020-10-11 21:21 UTC, dovahcrow approved these changes

2020-10-11 21:21 UTC, merged

2020-10-11 21:21 UTC, dovahcrow commented
Thank you @pallavibharadwaj !