chore: Modify Connector section - README.md file
sfu-db/dataprep pull request #389
Opened 2020-10-14 04:36 UTC by juandavidospina

# Description

Updating the "Connector" section in the README.md file. Three new animations were included (connector_main.gif, connector_pagination.gif, and connector_concurrency.gif) plus updates in descriptions and content. Closes #281.

# How Has This Been Tested?

Content verified using Markdown editor.

# Snapshots:

![image](https://user-images.githubusercontent.com/21973854/95943478-cc618580-0d9a-11eb-944a-49ae29467047.png)

![image](https://user-images.githubusercontent.com/21973854/95943502-dc796500-0d9a-11eb-86ce-f9ca1f2bcdce.png)

![image](https://user-images.githubusercontent.com/21973854/95943529-ebf8ae00-0d9a-11eb-9683-f2dfbfef723e.png)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [x] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2020-10-16 18:49 UTC, peiwangdb commented on README.md
> +Connector provides a simple programming interface to collect structured data from different Web APIs (e.g., Twitter API, Yelp Fusion API, Spotify API, DBLP API), making web data collection easy and e
Change to the value proposition sentence.

2020-10-25 01:01 UTC, dovahcrow requested changes
I think there are still some changes from the last meeting?

2020-10-26 21:19 UTC, juandavidospina commented
@dovahcrow Right. They are in progress. Target date: 2020-10-28.

2020-10-29 21:55 UTC, juandavidospina commented
Replaced by #404.

2020-10-29 21:55 UTC, closed without merging