feat(eda): enrich plot_correlation
sfu-db/dataprep pull request #414
Opened 2020-11-05 14:56 UTC by yuzhenmao

# Description

Fixes #394 - EDA.plot_correlation: enrich with stat. I only implemented it under the situation: plot_correlation(df) 

# How Has This Been Tested?

manually

# Snapshots:

![C4Z`1P4_(7JU6D1_}U$J3~8](https://user-images.githubusercontent.com/57878927/98256863-0b5db200-1fba-11eb-8b94-18dd3a68cc3e.png)

![24TI22HUT%9 RS7}2U 75_R](https://user-images.githubusercontent.com/57878927/98256870-0c8edf00-1fba-11eb-8cb5-f2c15bf8dcba.png)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [x] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2020-11-07 13:38 UTC, yuzhenmao commented
Now it can show the top-6 column-pairs
![1DQ1XA}EJARE }ZNR AAYY](https://user-images.githubusercontent.com/57878927/98442750-8b625400-2141-11eb-8237-17aa0b7ed87c.png)

2020-11-12 10:51 UTC, yuzhenmao commented
Now it is like this:

![X 2E7ESREA~N`KMNY 24FFV](https://user-images.githubusercontent.com/57878927/98930767-08157980-2518-11eb-8606-ac44a7b42862.png)

2020-11-17 08:13 UTC, jinglinpeng requested changes

2020-11-17 08:13 UTC, jinglinpeng commented on dataprep/eda/correlation/compute/nullivariate.py
> +
Seems the processing of each correlation type is the same. Could we write a function to reduce the duplicate code? Besides, the variable name is not self-explained. Would be better to use full name.

2020-11-17 08:13 UTC, jinglinpeng commented on dataprep/eda/correlation/compute/nullivariate.py
> +    p_col_set = set()
the variable name is not self-explained, and change it to full name. (E.g., `positive_col_set`?)

2020-11-19 08:31 UTC, jinglinpeng approved these changes

2020-11-19 08:31 UTC, merged