feat(clean): add clean_address function
sfu-db/dataprep pull request #494
Opened 2021-02-03 22:57 UTC by ryanwdale

# Description

Implements the `clean_address()` and `validate_address()` functions for cleaning messy addresses.

# How Has This Been Tested?

Unit tests are provided and snapshots are below.

# Snapshots:

### Default clean_address

![Screen Shot 2021-02-03 at 2 53 53 PM](https://user-images.githubusercontent.com/47376068/106820237-d7813f80-662f-11eb-9767-75d4c2abbcea.png)

### `split` parameter

![Screen Shot 2021-02-03 at 2 54 06 PM](https://user-images.githubusercontent.com/47376068/106820264-e8ca4c00-662f-11eb-8e3c-66b544929af6.png)

### `output_format` parameter 

![Screen Shot 2021-02-03 at 2 54 15 PM](https://user-images.githubusercontent.com/47376068/106820306-f67fd180-662f-11eb-8e32-e6c3d11232bf.png)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [ ] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-02-05 04:50 UTC, brandonlockhart requested changes
Excellent PR Ryan! I just left a couple of minor comments.

Can you also please follow the instructions [here](https://github.com/sfu-db/dataprep/wiki/Docstring-Best-Practice#auto-generating-the-api-reference) and add the modified file to this PR?

After these changes, I think it can be merged.

2021-02-05 04:50 UTC, brandonlockhart commented on dataprep/clean/clean_address.py
> +    address_str = address_str.replace("(", "")
What do you think about `address_str = re.sub(r"[().]", "", address_str)` here? Maybe it's a bit more concise.

2021-02-05 04:50 UTC, brandonlockhart commented on dataprep/clean/clean_address.py
> +    keywords = [
Can this be made a global variable?

2021-02-05 04:50 UTC, brandonlockhart commented on dataprep/clean/clean_address.py
> +        return None, "unknown"
Should this be `return (None, "unknown") if clean else False`?

2021-02-06 00:16 UTC, ryanwdale commented
Thanks Brandon, I agree with all your comments and I've made the requested changes.

2021-02-06 01:37 UTC, brandonlockhart approved these changes
LGTM

2021-02-06 01:38 UTC, merged