Feature(Connector): Function to allow dynamic website generation
sfu-db/dataprep pull request #545
Opened 2021-03-25 07:40 UTC by Lakshay-sethi

# Description

This PR request is in relation  to issue #544 .

# How Has This Been Tested?

In order to test it I created a mapbox named folder which contains some config file(to be deleted after PR is approved).
Alongside of it I created a juypter notebook which contains the code I used to test it.

# Snapshots:
with parse = True
![image](https://user-images.githubusercontent.com/58126894/112435776-6e01e100-8d02-11eb-8d16-4fcbaba35d50.png)
 
With parse = false (Default)
![image](https://user-images.githubusercontent.com/58126894/112435923-9f7aac80-8d02-11eb-99da-b0423ce171fb.png)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have already squashed the commits and make the commit message conform to the project standard.
- [ ] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-25 16:04 UTC, peiwangdb commented
Great job! @Lakshay-sethi , just tested with the notebook. The info function seems to be strange on my side. Is this what supposed to be shown? Will get back to you with more details.
<img width="338" alt="Screen Shot 2021-03-25 at 8 59 20 AM" src="https://user-images.githubusercontent.com/15167104/112504154-be9c2d00-8d48-11eb-9279-8136329ab17c.png">

2021-03-25 18:04 UTC, Lakshay-sethi commented
yes, this what it is supposed to do since it is a test config file, not all things were added.

2021-03-25 23:26 UTC, peiwangdb commented
Update: 'daily' table does not work, the second test case also failed with 404.

2021-03-25 23:39 UTC, Lakshay-sethi commented
Additional info:
I have no clue but daily config is will work sometimes and sometimes it will not.
Main test target is places. I will try to find the issue with daily.

2021-03-26 04:21 UTC, Lakshay-sethi commented on dataprep/connector/info.py
> +            print(table_config_content.request.urlParse)
This will be converted into the format currently used if my design gets passed.

2021-03-26 04:24 UTC, Lakshay-sethi commented on dataprep/connector/connector.py
> +################################################################
This is a shortcut I had to use, currently if a person enters a parameter like name, and name is not present in config file. The code throws an error, so in order to make my code ready for initial view I manually entered the variables in the allowed_params set.

Need to find a permanent way to resolve this issue, with the help of the designer of this file.

2021-03-30 04:02 UTC, nick-zrymiak reviewed
- I would say it might be best to make this PR separate from the mapbox PR
- I think tests should be .py files and included in the directory of other connector tests

2021-03-30 21:56 UTC, Lakshay-sethi commented on dataprep/connector/connector.py
> +    return url
done

2021-03-30 21:57 UTC, Lakshay-sethi commented on dataprep/connector/connector.py
> +    """Changes the a url by adding required parameters directly to the url.
done

2021-03-30 21:57 UTC, Lakshay-sethi commented on dataprep/connector/connector.py
> +        #
done

2021-04-01 02:16 UTC, dovahcrow commented
@Lakshay-sethi 
You can take a look at the code and let me know if you have any comments. 

you can use the following configuration file with the code `df = await dc.query("places", search_text="a")` to test.

places.json:
```json
{
    "version": 1,
    "request": {
        "url": "http://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json",
        "method": "GET",
        "authorization": {
            "type": "QueryParam",
            "keyParam": "access_token"
        },
        "params": {
            "proximity": false
        }
    },
    "response": {
        "ctype": "application/json",
        "tablePath": "$.features[*]",
        "schema": {
            "id": {
                "target": "$.type",
                "type": "string"
            },
            "type": {
                "target": "$.type",
                "type": "string"
            },
            "place_name": {
                "target": "$.type",
                "type": "string"
            },
            "bbox": {
                "target": "$.bbox",
                "type": "list"
            },
            "url": {
                "target": "$.center",
                "type": "list"
            }
        },
        "orient": "records"
    }
}
```

2021-04-01 05:46 UTC, dovahcrow requested changes
Please take a look at my reply above.

2021-04-01 19:30 UTC, Lakshay-sethi commented
The code looks code, how are you handling the case when the user doesn't want to parse

2021-04-01 20:07 UTC, dovahcrow commented
@Lakshay-sethi 

"url": {
    "url": "http://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json",
    "parse: false
}

2021-04-01 20:08 UTC, merged